version: '3.9'

services:
  client:
    build: ./client
    ports:
      - "5173:80" 
    depends_on:
      - server
    networks:
      - lognet

  server:
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server/logs/log.json:/app/logs/log.json
    networks:
      - lognet

networks:
  lognet:
    driver: bridge
