version: '3.9'

services:
  client:
    build: ./client
    ports:
      - "5173:80"
    volumes:     # only development mode without build again when any changes done in code, I need to remove this on production mode.
      - ./client:/app 
    depends_on:
      - server
    networks:
      - lognet

  server:
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app  # only development mode without build again when any changes done in code, I need to remove this on production mode.
      - ./server/logs/log.json:/app/logs/log.json
    networks:
      - lognet

networks:
  lognet:
    driver: bridge
